server:
  port: 9002
spring:
  application:
    name: tensquare_recruit
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.73.128:3306/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true

